### ISSUE TITLE
CodeCapybara

### ISSUE THREAD

**Issue by artemox** [wsxiaoys/awesome-ai-coding#2]
https://github.com/AI4Code-Research/CodeCapybara

**Comment by wsxiaoys** [comment]
Thanks, would you like to send an PR to add it to the  `Projects` part?

**Comment by wsxiaoys** [comment]
done in https://github.com/wsxiaoys/awesome-ai-coding/commit/182392ce0d0e2a26ac4af6e1d94d930018591b43
